apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-gc-backup
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-gc-backup
              image: dazlabteam/postgres-gc-backup
              envFrom:
                - secretRef:
                    name: postgres-gc-backup
          restartPolicy: Never
